# Workflow name
name: Pack .NET Project
inputs:
  projectDir:
    required: true
    type: string
  outputZip:
    required: true
    type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
runs:
  using: "composite"
  steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      shell: pwsh
      with:
        dotnet-version: |
          6.0.x

    - name: NuGet Restore
      run: dotnet restore
      shell: pwsh

    - name: Build
      run: dotnet build -c Release ${{ inputs.projectDir }} --no-restore
      shell: pwsh

    - name: Test
      run: dotnet test ${{ inputs.projectDir }} --no-restore --verbosity normal
      shell: pwsh

    - name: Publish
      run: dotnet publish --no-build --configuration Release ${{ inputs.projectDir }} --output ./publish
      shell: pwsh

    - name: Compress Archive
      run: Compress-Archive -Path ./publish/* -DestinationPath ${{ inputs.outputZip }}
      shell: pwsh

    - name: Upload Build Artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v2
      shell: pwsh
      with:
        path: ${{ inputs.outputZip }}
