# Workflow name
name: Deploy

# Controls when the workflow will run
on:
  # This is a reusable workflow
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment_url:
        required: false
        type: string

defaults:
  run:
    shell: pwsh

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/deploy-infra.yml
        with:
          environment: ${{ inputs.environment }}

      - uses: ./.github/workflows/deploy-code.yml
        with:
          environment: ${{ inputs.environment }}
