# Workflow name
name: Deploy

# Controls when the workflow will run
on:
  # This is a reusable workflow
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment_url:
        required: false
        type: string

defaults:
  run:
    shell: pwsh

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/deploy-infra
        with:
          environment: ${{ inputs.environment }}
          AZURE_CREDENTIALS: ${{ env.AZURE_CREDENTIALS }}

      - uses: ./.github/actions/deploy-code
        with:
          environment: ${{ inputs.environment }}
          AZURE_CREDENTIALS: ${{ env.AZURE_CREDENTIALS }}
