# Workflow name
name: Pack .NET Project

# Controls when the workflow will run
on:
  # This is a reusable workflow
  workflow_call:
    inputs:
      projectDir:
        required: true
        type: string
      outputZip:
        required: true
        type: string

defaults:
  run:
    shell: pwsh

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x

      - name: NuGet Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release ${{ inputs.projectDir }} --no-restore

      - name: Test
        run: dotnet test ${{ inputs.projectDir }} --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish --no-build --configuration Release ${{ inputs.projectDir }} --output ./publish

      - name: Compress Archive
        run: Compress-Archive -Path ./publish/* -DestinationPath ${{ inputs.outputZip }}

      - name: Upload Build Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          path: ${{ inputs.outputZip }}
