name: TerrariaMate

on:
  push:
    branches: [main]
    paths-ignore:
      - .gitignore
  pull_request:
    branches: [main]
    paths-ignore:
      - .gitignore
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: pwsh

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/reusable/publish-code.yml

  deploy_dev:
    needs: publish
    runs-on: ubuntu-latest
    environment:
      name: DEV
    steps:
      - uses: ./.github/workflows/reusable/deploy.yml
        with:
          environment: "DEV"

  deploy_prod:
    needs: [publish, deploy_dev]
    runs-on: ubuntu-latest
    environment:
      name: PROD
      url: https://terrariamate.com
    steps:
      - uses: ./.github/reusable/deploy.yml
        with:
          environment: "PROD"
