name: TerrariaMate

on:
  push:
    branches: [main]
    paths-ignore:
      - .gitignore
  pull_request:
    branches: [main]
    paths-ignore:
      - .gitignore
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: pwsh

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  publish:
    uses: ./.github/workflows/publish-code.yml
    needs: prepare

  deploy_dev:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "DEV"
    needs: publish

  deploy_prod:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "PROD"
    needs: deploy_dev
    environment:
      name: PROD
      url: https://terrariamate.com
