name: TerrariaMate

on:
  push:
    branches: [main]
    paths-ignore:
      - .gitignore
  pull_request:
    branches: [main]
    paths-ignore:
      - .gitignore
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: pwsh

jobs:
  publish:
    steps:
      - uses: ./.github/workflows/reusable/publish-code

  deploy_dev:
    environment:
      name: DEV
    steps:
      - uses: ./.github/workflows/reusable/deploy
        with:
          environment: "DEV"

  deploy_prod:
    environment:
      name: PROD
      url: https://terrariamate.com
    steps:
      - uses: ./.github/reusable/deploy
        with:
          environment: "PROD"
